# Default configuration
host: "0.0.0.0"
interval: 60s
servers:
  # First Light servers
  # 
  # Deer Isle
  - ip: "50.108.13.235"
    port: 2424
  # Deer Isle Hardcore
  - ip: "50.108.13.235"
    port: 2324
  # Namalsk Hardcore
  - ip: "50.108.13.235"
    port: 2315
  # Frostline
  - ip: "50.108.13.235"
    port: 27016
