# Default configuration
host: "localhost"
interval: 60s
servers:
  # First Light servers
  # 
  - name: "Deer Isle"
    ip: "50.108.13.235"
    port: 2424
  - name: Deer Isle Hardcore
    ip: "50.108.13.235"
    port: 2324
  - name: Namalsk Hardcore
    ip: "50.108.13.235"
    port: 2315
  - name: Frostline
    ip: "50.108.13.235"
    port: 27016
